layout_spectrum: 0.190825
color:
  saturation: 0.5284479
  lightness: 0.2216213
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#E0C56F'
    - '#FAF0CE'
    - '#916528'
    - '#99886E'
  rhythmicContrast: 0.3706723
typography_spectrum: 0.387218
name: Darpananand.com
