name: www.darpananand.com
favicon: null
layout_spectrum: 0.190825
typography_spectrum: 0.387218
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Darpan Anand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#E0C56F'
    - '#FAF0CE'
    - '#916528'
    - '#99886E'
  brandStrength: 1
  lightness: 0.2216213
  saturation: 0.5284479
  rhythmicContrast: 0.3706723
purpose: []
